
import { Medicine, FAQItem, Testimonial, LabTestDetail, LabPackageDetail, LabReview, City } from './types';

export const MEDICINES: Medicine[] = [
    {
        id: '1',
        name: 'Ecosprin 75 Tablet',
        brand: 'USV Ltd',
        price: 4.83,
        mrp: 5.50,
        packSize: 'Strip of 14 tablets',
        imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/b2f3058a-502c-429c-9b7b-55d3862768bf.png',
        images: ['https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/b2f3058a-502c-429c-9b7b-55d3862768bf.png', 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/e4e2c656-7006-4471-916f-74c62c87201e.png'],
        description: 'Ecosprin 75 Tablet is an antiplatelet medicine used to prevent and treat heart attacks, strokes, and angina (heart-related chest pain). It helps to prevent the formation of blood clots in your blood vessels.',
        contains: 'Aspirin (75mg)',
        therapy: 'Antiplatelet',
        uses: ['Prevention of heart attack', 'Prevention of stroke', 'Angina (Heart-related chest pain)'],
        contraindications: ['Allergy to Aspirin', 'Bleeding disorders', 'Stomach ulcers'],
        sideEffects: ['Heartburn', 'Increased bleeding tendency', 'Nausea', 'Upset stomach'],
        precautions: [
            { title: 'Alcohol', advice: 'Unsafe. It may increase the risk of stomach bleeding.' },
            { title: 'Pregnancy', advice: 'Consult your doctor. It may affect the baby.' },
            { title: 'Driving', advice: 'Safe. It does not usually affect your ability to drive.' },
        ],
        howToUse: 'Take this medicine in the dose and duration as advised by your doctor. Swallow it as a whole. Do not chew, crush or break it. Ecosprin 75 Tablet is to be taken with food.',
        storage: 'Store below 30°C',
        quickTips: [
            'Take it with food to avoid stomach upset.',
            'It may increase your risk of bleeding. Be careful while shaving or cutting fingernails.',
            'Notify your doctor if you notice black stools or vomit blood.',
        ],
        dosage: {
            overdose: 'Seek emergency medical attention or call the Poison Help line.',
            missedDose: 'Take the missed dose as soon as you remember. Skip the missed dose if it is almost time for your next scheduled dose. Do not take extra medicine to make up the missed dose.',
        },
        modeOfAction: 'Ecosprin 75 Tablet is a non-steroidal anti-inflammatory drug (NSAID) with anti-platelet action. It works by preventing platelets from sticking together which decreases the formation of harmful blood clots.',
        interactions: 'May interact with blood thinners like Warfarin, Steroids, and Painkillers.',
        productFaqs: [
            { question: 'Is Ecosprin 75 Tablet a blood thinner?', answer: 'Yes, it is an antiplatelet medicine that thins the blood.' },
            { question: 'Can I stop taking Ecosprin 75 Tablet on my own?', answer: 'No, do not stop taking it without consulting your doctor as it may increase your risk of heart attack or stroke.' },
        ]
    },
    {
        id: '2',
        name: 'Dolo 650 Tablet',
        brand: 'Micro Labs Ltd',
        price: 30.91,
        mrp: 35.00,
        packSize: 'Strip of 15 tablets',
        imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/573d0314-6951-4a40-ad27-655949a2c557.jpg',
        description: 'Dolo 650 Tablet helps relieve pain and fever by blocking the release of certain chemical messengers that cause fever and pain.',
        contains: 'Paracetamol (650mg)',
        therapy: 'Analgesic and Antipyretic',
        uses: ['Fever', 'Headache', 'Muscle pain', 'Menstrual cramps'],
        contraindications: ['Severe liver disease', 'Allergy to Paracetamol'],
        sideEffects: ['Nausea', 'Vomiting', 'Stomach pain'],
        precautions: [
            { title: 'Alcohol', advice: 'Unsafe. Increases risk of liver damage.' },
            { title: 'Pregnancy', advice: 'Safe if used as prescribed.' },
        ],
        howToUse: 'Swallow whole. Do not crush or chew. Can be taken with or without food.',
        storage: 'Store in a cool dry place.',
        quickTips: ['Do not take with other paracetamol-containing medicines.', 'Avoid alcohol while taking this medicine.'],
        dosage: { overdose: 'Seek medical help immediately.', missedDose: 'Take as soon as remembered. Do not double dose.' },
        modeOfAction: 'Inhibits prostaglandin synthesis in the CNS.',
        interactions: 'Interacts with Nimesulide, Metoclopramide.',
        productFaqs: [
            { question: 'Is Dolo 650 safe for kids?', answer: 'Consult a pediatrician for appropriate dosage for children.' },
        ]
    },
     {
        id: '3',
        name: 'Vitamin C Chewable',
        brand: 'Abbott',
        price: 22.50,
        mrp: 25.00,
        packSize: 'Strip of 15 tablets',
        imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/10482712-7166-4883-8673-107c4050787f.jpg',
        description: 'Limcee 500mg Tablet Orange is used to treat Vitamin C deficiency and helps boost immunity.',
        contains: 'Vitamin C / Ascorbic Acid (500mg)',
        therapy: 'Nutritional Supplement',
        uses: ['Vitamin C deficiency', 'Immunity boosting'],
        contraindications: ['Hyperoxaluria'],
        sideEffects: ['Nausea', 'Vomiting', 'Heartburn'],
        precautions: [],
        howToUse: 'Chew the tablet completely before swallowing.',
        storage: 'Store below 25°C',
        quickTips: ['Good for skin health.', 'Helps in wound healing.'],
        dosage: { overdose: 'May cause diarrhea.', missedDose: 'Take when remembered.' },
        modeOfAction: 'Essential for collagen formation and tissue repair.',
        interactions: 'May increase absorption of iron.',
        productFaqs: []
    },
    {
        id: '4',
        name: 'Shelcal 500 Tablet',
        brand: 'Torrent Pharmaceuticals',
        price: 115.00,
        mrp: 131.00,
        packSize: 'Strip of 15 tablets',
        imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/7f9e5201-103c-4379-b463-b52196a6009f.jpg',
        description: 'Shelcal 500 Tablet is a calcium supplement used to treat low blood calcium levels.',
        contains: 'Calcium (500mg) + Vitamin D3',
        therapy: 'Calcium Supplement',
        uses: ['Osteoporosis', 'Calcium deficiency'],
        contraindications: ['Hypercalcemia', 'Kidney stones'],
        sideEffects: ['Constipation', 'Stomach upset'],
        precautions: [{ title: 'Kidney Disease', advice: 'Caution advised.' }],
        howToUse: 'Take with food for better absorption.',
        storage: 'Store at room temperature.',
        quickTips: ['Drink plenty of water.'],
        dosage: { overdose: 'Consult doctor.', missedDose: 'Take as soon as possible.' },
        modeOfAction: 'Replenishes calcium and helps bone formation.',
        interactions: 'Interacts with Tetracycline antibiotics.',
        productFaqs: []
    }
];

export const PHARMACY_FAQS: FAQItem[] = [
    { question: 'Is it safe to buy medicines online?', answer: 'Yes, we ensure all medicines are sourced from licensed pharmacies and are 100% genuine.' },
    { question: 'Do I need a prescription?', answer: 'For certain scheduled drugs (Schedule H & H1), a valid prescription is mandatory. OTC products do not require one.' },
    { question: 'How can I track my order?', answer: 'You can track your order status in the "My Orders" section of the app or website.' },
    { question: 'What is the return policy?', answer: 'We have a 7-day return policy for damaged or incorrect items. Please check our return policy page for more details.' },
];

export const PHARMACY_TESTIMONIALS: Testimonial[] = [
    { name: 'Amit Sharma', location: 'Delhi', quote: 'Super fast delivery! Got my medicines within 2 hours. Highly recommended.' },
    { name: 'Priya Patel', location: 'Mumbai', quote: 'Genuine medicines and great discounts. The app is very easy to use.' },
    { name: 'Rahul Verma', location: 'Bangalore', quote: 'Customer support is excellent. They helped me find a substitute for a medicine that was out of stock.' },
    { name: 'Sneha Gupta', location: 'Hyderabad', quote: 'I order for my parents regularly. The subscription feature ensures they never run out of meds.' },
];

// --- Lab Data ---

export const CITIES: City[] = [
    { id: 'mumbai', name: 'Mumbai' },
    { id: 'delhi', name: 'Delhi' },
    { id: 'bengaluru', name: 'Bengaluru' },
    { id: 'hyderabad', name: 'Hyderabad' },
    { id: 'pune', name: 'Pune' },
    { id: 'kolkata', name: 'Kolkata' },
    { id: 'ahmedabad', name: 'Ahmedabad' },
    { id: 'chennai', name: 'Chennai' },
    { id: 'jaipur', name: 'Jaipur' },
    { id: 'nagpur', name: 'Nagpur' },
];

export const LAB_TESTS_DATA: LabTestDetail[] = [
    {
        id: 'cbc',
        name: 'Complete Blood Count (CBC)',
        alias: 'Hemogram',
        testCount: 25,
        fasting: 'Not Required',
        reportTime: '24 Hrs',
        price: 299,
        mrp: 400,
        discount: '25%',
        sampleType: 'Blood',
        tubeType: 'EDTA',
        category: 'CBC Test',
        rating: 4.8,
        reviewCount: 1250,
        description: 'A Complete Blood Count (CBC) is a blood test used to evaluate your overall health and detect a wide range of disorders, including anemia, infection and leukemia.',
        whyItMatters: 'A complete blood count (CBC) test gives your doctor a snapshot of your overall health. It measures many parts of your blood, including red blood cells, white blood cells, and platelets. Abnormal levels can signal issues like infection, anemia, or clotting disorders.',
        parameters: ['Red Blood Cells (RBC)', 'White Blood Cells (WBC)', 'Platelet Count', 'Hemoglobin', 'Hematocrit', 'MCV', 'MCH', 'MCHC', 'RDW'],
    },
    {
        id: 'crp',
        name: 'C-Reactive Protein (CRP)',
        alias: 'CRP Quantitative',
        testCount: 1,
        fasting: 'Not Required',
        reportTime: '24 Hrs',
        price: 399,
        mrp: 550,
        discount: '27%',
        sampleType: 'Blood',
        tubeType: 'Serum',
        category: 'CRP Test',
        rating: 4.7,
        reviewCount: 890,
        description: 'C-reactive protein (CRP) is a substance produced by the liver in response to inflammation. This test measures the amount of CRP in the blood.',
        whyItMatters: 'High levels of CRP are caused by inflammation due to various conditions such as infection, autoimmune disorders, or chronic diseases. It is a key marker for heart disease risk assessment.',
        parameters: ['C-Reactive Protein (Quantitative)'],
    },
    {
        id: 'lipid',
        name: 'Lipid Profile',
        alias: 'Cholesterol Test',
        testCount: 9,
        fasting: '10-12 Hrs',
        reportTime: '24 Hrs',
        price: 599,
        mrp: 1000,
        discount: '40%',
        sampleType: 'Blood',
        tubeType: 'Serum',
        category: 'Lipid Profile Test',
        rating: 4.9,
        reviewCount: 2100,
        description: 'The lipid profile helps to screen for abnormalities in lipids, such as cholesterol and triglycerides.',
        whyItMatters: 'This test is crucial for assessing your risk of cardiovascular disease. High levels of bad cholesterol (LDL) can lead to plaque buildup in arteries, increasing the risk of heart attack and stroke.',
        parameters: ['Total Cholesterol', 'Triglycerides', 'HDL Cholesterol (Good)', 'LDL Cholesterol (Bad)', 'VLDL Cholesterol', 'Total/HDL Ratio', 'LDL/HDL Ratio'],
    },
    {
        id: 'thyroid',
        name: 'Thyroid Profile (Total)',
        alias: 'T3, T4, TSH',
        testCount: 3,
        fasting: 'Not Required',
        reportTime: '24 Hrs',
        price: 499,
        mrp: 800,
        discount: '38%',
        sampleType: 'Blood',
        tubeType: 'Serum',
        category: 'Thyroid Profile Test',
        rating: 4.8,
        reviewCount: 1800,
        description: 'A group of tests to measure thyroid function and diagnose thyroid disorders.',
        whyItMatters: 'The thyroid gland controls metabolism. Imbalances can cause weight changes, fatigue, and mood swings. This test checks if your thyroid is overactive (hyperthyroidism) or underactive (hypothyroidism).',
        parameters: ['Triiodothyronine (T3)', 'Thyroxine (T4)', 'Thyroid Stimulating Hormone (TSH)'],
    },
    {
        id: 'hba1c',
        name: 'HbA1c',
        alias: 'Glycosylated Hemoglobin',
        testCount: 1,
        fasting: 'Not Required',
        reportTime: '24 Hrs',
        price: 350,
        mrp: 500,
        discount: '30%',
        sampleType: 'Blood',
        tubeType: 'EDTA',
        category: 'HbA1c Test',
        rating: 4.9,
        reviewCount: 3200,
        description: 'The HbA1c test measures your average blood sugar levels over the past 3 months.',
        whyItMatters: 'It is the primary test used for diabetes management and research. Unlike a daily finger-prick test, it provides a long-term trend of your blood sugar control.',
        parameters: ['HbA1c Level', 'Average Blood Glucose'],
    },
];

export const LAB_PACKAGES_DATA: LabPackageDetail[] = [
    {
        id: 'fullbody',
        name: 'Comprehensive Full Body Checkup',
        testCount: 85,
        fasting: '10-12 Hrs',
        reportTime: '48 Hrs',
        price: 1499,
        mrp: 3999,
        discount: '62%',
        rating: 4.8,
        reviewCount: 540,
        idealFor: 'Men & Women (25+ Yrs)',
        description: 'A complete health assessment including Liver, Kidney, Lipid, Thyroid, Iron, and Vitamin profiles.',
        testsIncluded: ['CBC', 'Lipid Profile', 'Liver Function Test', 'Kidney Function Test', 'Thyroid Profile', 'Iron Studies', 'Vitamin D', 'Vitamin B12', 'Urine Routine'],
    },
    {
        id: 'diabetes',
        name: 'Advanced Diabetes Care Package',
        testCount: 45,
        fasting: '10-12 Hrs',
        reportTime: '24 Hrs',
        price: 999,
        mrp: 2500,
        discount: '60%',
        rating: 4.7,
        reviewCount: 310,
        idealFor: 'Diabetic Patients',
        description: 'Designed for monitoring and managing diabetes with kidney and lipid checks.',
        testsIncluded: ['HbA1c', 'Fasting Blood Sugar', 'Lipid Profile', 'Kidney Function Test', 'Urine Microalbumin'],
    },
    {
        id: 'women',
        name: 'Women Wellness Package',
        testCount: 60,
        fasting: '10-12 Hrs',
        reportTime: '24 Hrs',
        price: 1299,
        mrp: 3200,
        discount: '59%',
        rating: 4.9,
        reviewCount: 420,
        idealFor: 'Women (30+ Yrs)',
        description: 'Tailored for women’s health needs including hormonal and nutritional profiles.',
        testsIncluded: ['CBC', 'Thyroid Profile', 'Iron Studies', 'Vitamin D', 'Calcium', 'FSH', 'LH', 'Prolactin'],
    }
];

export const LAB_REVIEWS: LabReview[] = [
    { id: '1', userName: 'Suresh Raina', date: '2 days ago', rating: 5, comment: 'Excellent service. The phlebotomist arrived on time and was very professional.' },
    { id: '2', userName: 'Anjali Menon', date: '1 week ago', rating: 4, comment: 'Reports were delivered on time via email. Good experience.' },
    { id: '3', userName: 'Vikram Singh', date: '3 weeks ago', rating: 5, comment: 'Very affordable packages compared to local labs. Highly recommend.' },
];
